source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '~> 3.2.9'
gem 'unicorn'
gem 'memcachier'
gem 'dalli'
gem 'cache_digests'

gem '<%= @template_language %>-rails'

gem 'pg'
# gem 'postgres_ext'
gem 'seedbank', require: false

# gem 'delocalize'
gem 'inherited_resources'
gem 'responders'
gem 'strong_parameters'

# gem 'simple_form'
# gem 'client_side_validations'
# gem 'client_side_validations-simple_form'
# gem 'kaminari'
# gem 'actionmailer_inline_css'
# gem 'menu_builder'

group :development, :test do
  gem 'rb-inotify', require: false

  gem 'factory_girl_rails', require: false
  gem 'forgery',            require: false

  gem 'guard',               require: false
  gem 'guard-bundler',       require: false
  gem 'guard-rspec',         require: false
  gem 'guard-ctags-bundler', require: false
  gem 'guard-jasmine',       require: false

  gem 'rspec-rails'
  gem 'database_cleaner', require: false
  gem 'simplecov',        require: false
  gem 'rspec-spies',      require: false
  gem 'rspec-fire',       require: false
  gem 'shoulda-matchers', require: false

  gem 'poltergeist',    require: false
  gem 'capybara',       require: false
  gem 'capybara-email', require: false

  gem 'jasminerice'

  gem 'debugger'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rails-footnotes'
  gem 'bullet'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier',     '>= 1.0.3'
  gem 'asset_sync'

  gem 'jquery-rails'
  # gem 'jquery-ui-rails'
  # gem 'backbone-on-rails'
  # gem 'bootstrap-sass-rails'
end
