#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

<%= app_const %>.load_tasks

if %w(development test).include? Rails.env
  require 'guard/jasmine/task'
  Guard::JasmineTask.new

  Rake::Task[:default].clear
  task :default => [:coverage, 'guard:jasmine']
end
